steps:
  - label: ":hammer: test"
    plugins:
      docker-compose#v1.3.1:
        run: tests
  - label: ":sparkles: lint"
    plugins:
      plugin-linter#v2.0.0:
        id: lambdatest/lambdatest-plugin
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/**
